public class CollegeRecords {
     private String First_Name;
     private String Last_Name;
     private Integer Roll_Number;
     private string father_Name;
    
public void input(String FirstName,String LastName,Integer Rollnumber, string fatherName){
        First_Name = FirstName;
        Last_Name= LastName;
        Roll_number= Rollnumber;
        father_Name=fathername;     
    }
public void output(){
       System.debug('First Name    :'   +First_Name);
       System.debug('Last  Name    :'   +Last_Name);    
       System.debug('Roll Number   :'   +Roll_number);
       System.debug('Father Name   :'   +father_Name);
        
    }   
   
}