@isTest
  public class EmployeeTest {
      static testMethod void main(){
      Employee emp_obj1 = new Employee();
          emp_obj1.getValues();
          emp_Obj1.setValues('xyz',172345,'Male',5.9);
          emp_obj1.getValues();
        Employee emp_obj2 = new Employee();
          emp_obj2.getValues();
          emp_Obj2.setValues('PQRS',182435,'Male',6.0);
          emp_obj2.getValues();
      }    
}