@isTest
public class MCtest {
    public static testMethod void anyname(){
        Employee ba_obj1 = new Employee();  
        //Sobject obj = new Sobject
        Campaign cmp1 = new Campaign();
        Lead lm1 = new Lead();
        Account ac1 = new Account();
        Contact cm1= new contact();// Standard Objects
        Opportunity opp1 = new Opportunity();
        Course__c cs1 = new Course__C();// Custom Object 
      //
    }
}