@istest
//public class rectangletestclass {
   // static testMethod void anyname(){
        //create object with DC
        //
                                                  // count before any object is created ??
        
        //rectangle.getcount();
       // rectangle board = new rectangle();//board is created 
        //Load length and breadth values for this object 
         //board.setValues(12,34); //it is loaded with the meaningfull values 
        //system.debug('Dimensions of the Board:');
       // board.getValues();
        //create an object with PC
       // rectangle inko_board = new rectangle (32,44); // inko board is created with the meaningfull
       // system.debug('Dimensions of the board :');
        //inko_board.getValues();
        //Integer res= 10 + 20 ;
        //Integer ar_ib= inko_board.calcArea();
        //Integer cost = 25 * ar_ib;
        //System.debug('cost of the Inko board is ' +cost);
       // inko_board.getcount();//       Object.method will provide services// how to access member using dot operator(.)
       // rectangle window = new rectangle();
       // window.getcount();
       // rectangle laptop = new rectangle();
        //inko_board.getcount();
        //rectangle slate = new rectangle();
       // inko_board.getcount();
        //rectangle mirror = new rectangle();
        //inko_board.getcount();
    //}

//}





public class rectangletestclass {
   static testMethod void anyname(){
      
        rectangle.getcount();
        rectangle board = new rectangle();//board is created 
        rectangle.getcount();
        rectangle window = new rectangle();
        rectangle.getcount();
        rectangle laptop = new rectangle();
        rectangle.getcount();
        rectangle slate = new rectangle();
        rectangle.getcount();
        rectangle mirror = new rectangle();
        rectangle.getcount();
    }

}