@isTest
public class TangerOutletstoretest {
   static testMethod void main(){
        TangerOutletStore Tang_obj1 = new TangerOutletStore();
            Tang_obj1.setValues(23, 'pqrst',99999,'Male',172.23);
            Tang_obj1.getValues();
       TangerOutletStore Tang_obj2 = new TangerOutletStore();
            Tang_obj2.setValues(55,'ethan',454555,'Male',144.34);
            Tang_obj2.getValues();
    }
    
}