@istest
public class WalmartStoretest {
    static testMethod void main(){
     WalmartStore wal_obj11 = new WalmartStore();
        Wal_Obj11.getValues();
        Wal_Obj11.setValues('Patrick',123333,'Male',177.23);
        Wal_Obj11.getValues();
        WalmartStore wal_obj12 = new WalmartStore();
        Wal_Obj12.setValues('Nancy',6366363,'FeMale',123.23);
        Wal_Obj12.getValues();
    }      
}